---

- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v2.0.0
  hooks:
    - id: check-executables-have-shebangs
    - id: trailing-whitespace
    - id: check-yaml

- repo: https://github.com/ansible/ansible-lint.git
  rev: v3.5.1
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$

- repo: https://github.com/bemeurer/beautysh.git
  rev: "3.11"
  hooks:
    - id: beautysh

- repo: https://github.com/openstack-dev/bashate.git
  rev: "0.6.0"
  hooks:
    - id: bashate
