---

- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
  - files:
    - "{{ ansible_system }}_{{ ansible_architecture }}.yml"
    paths: vars

- name: Install on Linux
  include_tasks: Linux.yml
  when: ansible_system == 'Linux'

- name: Install on macOS
  include_tasks: Darwin.yml
  when: ansible_os_family == 'Darwin'
